import { MetadataRoute } from "next";
import { serviceCards } from "@/lib/servicesData";

export default function sitemap(): MetadataRoute.Sitemap {
  const baseUrl = "https://webdevelopmentai.in";

  // Static routes
  const staticRoutes = [
    "",
    "/about",
    "/portfolio",
    "/plans",
    "/cart",
    "/login",
    "/register",
    "/account",
    "/orders",
  ].map((route) => ({
    url: `${baseUrl}${route}`,
    lastModified: new Date(),
    changeFrequency: "weekly" as const,
    priority: route === "" ? 1 : 0.8,
  }));

  // Dynamic service plan routes
  const planRoutes = serviceCards.map((card) => ({
    url: `${baseUrl}/plans/${card.id}`,
    lastModified: new Date(),
    changeFrequency: "monthly" as const,
    priority: 0.7,
  }));

  // New Service Hubs & Blog routes
  const blogRoutes = [
    "/blog",
    "/services/raipur",
    "/services/ecommerce",
    "/services/business",
    "/services/marketing",
    "/more-services",
    "/services/education",
    "/services/manufacturing",
    "/industries/education",
    "/industries/healthcare",
    "/industries/manufacturing",
    "/industries/real-estate",
    "/industries/wholesale",
    "/ecommerce-website-bilaspur",
    "/blog/affordable-website-developer-raipur",
    "/blog/ai-se-website-banana-bilaspur",
    "/blog/ai-powered-vs-normal-website-differences",
    "/blog/ai-chatbot-business-raipur",
    "/blog/ai-vs-normal-website-raipur",
    "/blog/bakery-website-development-raipur",
    "/blog/bilaspur-mein-website-banwane-ka-kharcha",
    "/blog/business-website-raipur",
    "/blog/chhattisgarh-ke-liye-best-website-type",
    "/blog/chhattisgarh-local-business-website-guide",
    "/blog/ecommerce-website-development-raipur",
    "/blog/google-pe-website-kaise-aaye-bilaspur",
    "/blog/google-rank-bilaspur-business",
    "/blog/kyun-zaroori-hai-website-bilaspur",
    "/blog/kyun-fail-hota-hai-business-without-website",
    "/blog/online-store-kaise-banwayein-chhattisgarh",
    "/blog/ca-accountant-professional-website-guide",
    "/blog/salon-beauty-parlor-website-guide-bilaspur",
    "/blog/landing-page-kya-hota-hai-hindi-guide",
    "/blog/mp-gst-registration-website-benefits",
    "/blog/indore-photography-business-website-guide",
    "/blog/website-maintenance-importance-hindi-guide",
    "/blog/manufacturing-website-development-raipur",
    "/blog/nextjs-vs-wordpress-raipur",
    "/blog/raipur-bangalore-vs-local-developer",
    "/blog/raipur-vs-local-developer-bilaspur",
    "/blog/resiliencesoft-softwebian-alternative",
    "/blog/responsive-website-design-raipur",
    "/blog/restaurant-website-raipur",
    "/blog/sasti-website-raipur",
    "/blog/school-website-design-raipur",
    "/blog/seo-friendly-website-raipur",
    "/blog/small-business-website-raipur",
    "/blog/top-5-web-development-companies-raipur",
    "/blog/top-5-web-development-companies-raipur-honest-comparison",
    "/blog/website-banane-ka-kharcha-bilaspur-2026",
    "/blog/website-banane-ka-kharcha-raipur-2026",
    "/blog/website-cost-raipur",
    "/blog/website-development-cost-raipur",
    "/blog/website-ke-fayde-local-business",
    "/blog/why-website-important-raipur-business",
    "/blog/madhya-pradesh-online-business-shuru-karne-ka-tarika",
    "/blog/indore-textile-business-b2b-website-guide",
    "/blog/jabalpur-ecommerce-business-guide",
    "/blog/gwalior-property-dealers-website-guide",
    "/blog/voice-search-optimization-hindi-guide",
    "/blog/ai-chatbot-mp-business-guide",
    "/blog/whatsapp-online-shop-mp-guide",
    "/blog/mp-solar-business-website-guide-2026",
    "/blog/mp-hospital-online-appointment-system-guide",
    "/blog/school-management-software-website-mp-guide",
    "/blog/mp-ev-business-website-guide",
    "/blog/online-food-delivery-business-mp-guide",
    "/blog/mp-real-estate-website-cost-roi",
    "/blog/dropshipping-business-mp-hindi-guide",
    "/blog/mp-travel-agents-website-booking-guide",
    "/blog/drone-business-mp-agriculture-guide",
    "/blog/online-tuition-website-mp-teachers-guide",
    "/blog/mp-influencer-marketing-agency-website-guide",
    "/blog/mp-youtube-website-combo-guide",
    "/blog/indore-website-development-cost-2026",
    "/blog/indore-bhopal-ai-powered-web-developer",
    "/blog/website-design-company-in-bilaspur",
    "/blog/web-development-modern-tech-hindi-guide",
    "/blog/website-development-company-in-bilaspur",
    "/blog/ai-development-company-solutions",
    "/blog/ai-for-local-business-hindi-guide",
    "/blog/ai-web-development-agencies-vs-traditional",
  ].map((route) => ({
    url: `${baseUrl}${route}`,
    lastModified: new Date(),
    changeFrequency: "weekly" as const,
    priority: 0.9,
  }));

  return [...staticRoutes, ...planRoutes, ...blogRoutes];
}
